# Accélération et distance totale parcourue par un aéronef

Imaginons que l'on a des données de mesures provenant de capteurs d'aéronefs, la vitesse à différents instants dans le temps, et que l'on doit trouver:

1. L'accélération de l'avion à tout moment t
2. L'instant où la vitesse est maximale
3. La distance totale parcourue

Les données d'entrées sont fournies ci-dessous:

In [35]:
import numpy as np

# Données de temps (en secondes)
t = np.array([0, 12, 29, 31, 42, 54])

# Données de vitesse (en m/s)
v = np.array([105, 154, 223, 188, 251, 229])

## 1. Accélération

Calculez l'accélération de l'aéronef à chaque instant en utilisant la formule de base de la cinématique :

$ \alpha = \frac{\Delta_v}{\Delta_t}$

Utilisez les tableaux NumPy pour effectuer ces calculs de manière vectorisée et stockez les résultats dans un tableau appelé a.

In [36]:
# 1. Calcul de l'accélération
delta_t = np.diff(t)  # Calcul des variations de temps
delta_v = np.diff(v)  # Calcul des variations de vitesse

print(delta_t.shape)
print(delta_t)

print(delta_v.shape)
print(delta_v)

# Utilisation de la formule de la cinématique pour calculer l'accélération
a = delta_v / delta_t

print("\n On obtient l'accélération a:\n", a)

(5,)
[12 17  2 11 12]
(5,)
[ 49  69 -35  63 -22]

 On obtient l'accélération a:
 [  4.08333333   4.05882353 -17.5          5.72727273  -1.83333333]


## 2. Vitesse max

Pour trouver la vitesse max, on utilise la fonction de numpy qui s'applique à des ndarray `argmax` qui renvoie l'indice de l'élément maximum du tableau:

In [37]:
# 2. Moment où la vitesse maximale est atteinte
indice_max_vitesse = np.argmax(v)
temps_max_vitesse = t[indice_max_vitesse]
vitesse_max = v[indice_max_vitesse]

print("\n La vitesse est maximale pour l'indice:", indice_max_vitesse, "qui se produit pour t = ", temps_max_vitesse, "s")
print("\n La vitesse maximale est: ", vitesse_max, "m/s")


 La vitesse est maximale pour l'indice: 4 qui se produit pour t =  42 s

 La vitesse maximale est:  251 m/s


## 3. Distance totale parcourue

La distance totale parcourue est obtenue en intégrant la vitesse par rapport au temps. On utilise pour cela la fonction `trapz` qui effectue une integration numérique de l'un par rapport à l'autre.

In [38]:
# 3. Calcul de la distance totale parcourue
# Utilisation de la méthode des trapèzes pour l'intégration numérique
distance_totale = np.trapz(v, t)

print("La distance totale parcourue est:", distance_totale, "m")

La distance totale parcourue est: 10464.0 m


In [39]:
# Affichage des résultats
print("1. Accélération à chaque instant : ", a)
print("2. Moment où la vitesse maximale est atteinte : ", temps_max_vitesse, "s, Vitesse maximale : ", vitesse_max, "m/s")
print("3. Distance totale parcourue : ", distance_totale, "m")

1. Accélération à chaque instant :  [  4.08333333   4.05882353 -17.5          5.72727273  -1.83333333]
2. Moment où la vitesse maximale est atteinte :  42 s, Vitesse maximale :  251 m/s
3. Distance totale parcourue :  10464.0 m
